name: 'Deploy to GitHub Pages'
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '14'
        - name: Install dependencies
          run: npm install
        - name: vite Lint check
          run: npm run lint
    
    test:
      needs: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '14'
        - name: Install dependencies
          run: npm install
        - name: test 
          run: npm test
    
    deploy:
      needs: [lint, test]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '14'
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm build
        - name: Deploy
          run: echo 'Deploying...'