name: 'Deploy to GitHub Pages'
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
    run:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: Install dependencies
          run: npm install
        - name: vite Lint check
          run: npm run lint
        - name: Build
          run: npm build
        - name: test 
          run: npm test
        - name: Deploy
          run: echo 'Deploying...'