name: On Issues Checker
on:
  issues:
    types: [opened, edited, deleted]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Event Data
              run: echo "${{ toJson(github.event.issue) }}"